// <auto-generated />
using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using YUIFramework.Configuration;

namespace YUIFramework.ConfigGenerated
{

    public static class LocalizationTextConfig
    {
        public static ConfigTable<global::YUIFramework.Localization.LocalizationTextCatalog> Table =>
            global::YUIFramework.Localization.LocalizationTextCatalog.Table;
    }


    public static class UIPresentationConfig
    {
        public static ConfigTable<global::YUIFramework.Localization.UIPresentationCatalog> Table =>
            global::YUIFramework.Localization.UIPresentationCatalog.Table;
    }


    public sealed class UISettingsRow
    {
        public string Profile { get; }
        public string Id { get; }
        public string PrefabKey { get; }
        public string PrefabPackage { get; }
        public int Layer { get; }
        public bool CacheOnClose { get; }
        public int MaxPoolSize { get; }
        public int PreloadCount { get; }
        public int PoolPriority { get; }
        public float PoolIdleTimeoutSeconds { get; }
        public bool FullScreen { get; }
        public bool UseLayerModalPolicy { get; }
        public bool Modal { get; }
        public bool UseTransition { get; }
        public int TransitionType { get; }
        public float ShowDuration { get; }
        public float HideDuration { get; }
        public bool IgnoreTransitionTimeScale { get; }
        public float SlideDistance { get; }
        public float StartScale { get; }
        public string CustomTransitionId { get; }
        public bool RefreshTransitionBaselineOnReuse { get; }
        public bool SuspendWhenCovered { get; }

        internal UISettingsRow(string Profile, string Id, string PrefabKey, string PrefabPackage, int Layer, bool CacheOnClose, int MaxPoolSize, int PreloadCount, int PoolPriority, float PoolIdleTimeoutSeconds, bool FullScreen, bool UseLayerModalPolicy, bool Modal, bool UseTransition, int TransitionType, float ShowDuration, float HideDuration, bool IgnoreTransitionTimeScale, float SlideDistance, float StartScale, string CustomTransitionId, bool RefreshTransitionBaselineOnReuse, bool SuspendWhenCovered)
        {
            this.Profile = Profile;
            this.Id = Id;
            this.PrefabKey = PrefabKey;
            this.PrefabPackage = PrefabPackage;
            this.Layer = Layer;
            this.CacheOnClose = CacheOnClose;
            this.MaxPoolSize = MaxPoolSize;
            this.PreloadCount = PreloadCount;
            this.PoolPriority = PoolPriority;
            this.PoolIdleTimeoutSeconds = PoolIdleTimeoutSeconds;
            this.FullScreen = FullScreen;
            this.UseLayerModalPolicy = UseLayerModalPolicy;
            this.Modal = Modal;
            this.UseTransition = UseTransition;
            this.TransitionType = TransitionType;
            this.ShowDuration = ShowDuration;
            this.HideDuration = HideDuration;
            this.IgnoreTransitionTimeScale = IgnoreTransitionTimeScale;
            this.SlideDistance = SlideDistance;
            this.StartScale = StartScale;
            this.CustomTransitionId = CustomTransitionId;
            this.RefreshTransitionBaselineOnReuse = RefreshTransitionBaselineOnReuse;
            this.SuspendWhenCovered = SuspendWhenCovered;
        }
    }

    public sealed class UISettings
    {
        private readonly Dictionary<string, UISettingsRow> _rows;
        private UISettings(Dictionary<string, UISettingsRow> rows) => _rows = rows;
        public int Count => _rows.Count;
        public IReadOnlyCollection<UISettingsRow> Values => _rows.Values;
        public static ConfigTable<UISettings> Table { get; } =
            new ConfigTable<UISettings>("UISettings", true, Parse);

        public bool TryGet(string key0, string key1, out UISettingsRow row)
        {
            return _rows.TryGetValue(ConfigKey.Compose(key0, key1), out row);
        }

        public UISettingsRow Get(string key0, string key1)
        {
            if (_rows.TryGetValue(ConfigKey.Compose(key0, key1), out UISettingsRow row)) return row;
            throw new KeyNotFoundException($"配置 UISettings 不存在 Key: {ConfigKey.Display(key0, key1)}");
        }

        private static UISettings Parse(JToken root)
        {
            var rows = new Dictionary<string, UISettingsRow>(StringComparer.Ordinal);
            foreach (ConfigRowNode node in ConfigValue.EnumerateRows(root, 2, "UISettings"))
            {
                JToken[] keys = node.Keys;
                JObject row = node.Row;
                string key = ConfigKey.Compose(ConfigValue.ReadString(keys[0], "UISettings.Profile"), ConfigValue.ReadString(keys[1], "UISettings.Id"));
                var value = new UISettingsRow(
                    ConfigValue.ReadString(row, "Profile", "UISettings"),
                    ConfigValue.ReadString(row, "Id", "UISettings"),
                    ConfigValue.ReadString(row, "PrefabKey", "UISettings"),
                    ConfigValue.ReadOptionalString(row, "PrefabPackage", "UISettings"),
                    ConfigValue.ReadInt32(row, "Layer", "UISettings"),
                    ConfigValue.ReadBoolean(row, "CacheOnClose", "UISettings"),
                    ConfigValue.ReadInt32(row, "MaxPoolSize", "UISettings"),
                    ConfigValue.ReadInt32(row, "PreloadCount", "UISettings"),
                    ConfigValue.ReadInt32(row, "PoolPriority", "UISettings"),
                    ConfigValue.ReadSingle(row, "PoolIdleTimeoutSeconds", "UISettings"),
                    ConfigValue.ReadBoolean(row, "FullScreen", "UISettings"),
                    ConfigValue.ReadBoolean(row, "UseLayerModalPolicy", "UISettings"),
                    ConfigValue.ReadBoolean(row, "Modal", "UISettings"),
                    ConfigValue.ReadBoolean(row, "UseTransition", "UISettings"),
                    ConfigValue.ReadInt32(row, "TransitionType", "UISettings"),
                    ConfigValue.ReadSingle(row, "ShowDuration", "UISettings"),
                    ConfigValue.ReadSingle(row, "HideDuration", "UISettings"),
                    ConfigValue.ReadBoolean(row, "IgnoreTransitionTimeScale", "UISettings"),
                    ConfigValue.ReadSingle(row, "SlideDistance", "UISettings"),
                    ConfigValue.ReadSingle(row, "StartScale", "UISettings"),
                    ConfigValue.ReadOptionalString(row, "CustomTransitionId", "UISettings"),
                    ConfigValue.ReadBoolean(row, "RefreshTransitionBaselineOnReuse", "UISettings"),
                    ConfigValue.ReadBoolean(row, "SuspendWhenCovered", "UISettings"));
                if (key != ConfigKey.Compose(value.Profile, value.Id))
                    throw new ConfigDataException("Row key fields do not match their nested path.");
                if (!rows.TryAdd(key, value)) throw new ConfigDataException($"配置 UISettings 包含重复 Key: {key}");
            }
            if (rows.Count == 0) throw new ConfigDataException("Required table has no rows.");
            return new UISettings(rows);
        }
    }

    public static class GeneratedConfigCatalog
    {
        public static IReadOnlyList<string> Names { get; } = Array.AsReadOnly(new[]
        {
                "LocalizationTextConfig",
                "UIPresentationConfig",
                "UISettings"
        });

        public static IReadOnlyList<ConfigTable> Tables { get; } = Array.AsReadOnly(new ConfigTable[]
        {
            LocalizationTextConfig.Table,
            UIPresentationConfig.Table,
            UISettings.Table
        });
    }
}
